* Fremgang

** Hvilke en eller to hendelser i dag tydet på enten en liten seier eller et mulig gjennombrudd?

* Tilbakeslag

** Hvilke en eller to hendelser i dag tydet på enten et lite tilbakeslag eller krise i emning?

* Katalysatorer

** Hadde teamet klare kort- og langsiktige /mål/ for meningsfult arbeid?

** Hadde teamet tilstrekkelig /autonomi/ til å løse problemer og ta eierskap?

** Hadde alle de /ressursene/ de behøvde for å ha god fremgang?

** Hadde alle nok /tid/ til å fokusere på meningsfult arbeid?

** Ga eller ordnet jeg /hjelp/ ved behov eller forespørsel?

** Oppmuntrer jeg medlemmene i teamet til å hjelpe hverandre?

** Tok jeg opp /læring/ fra nylige seiere og problemer med teamet?

** Bidro jeg til /idéflyt/ i gruppen?

* Inhibitorer

** Var det noen forvirring om kort- og langsiktige /mål/ for meningsfult arbeid?

** Hadde teamet noe som /begrenset/ dets mulighet til å løse problemer og ta eierskap?

** Manglet teamet /ressursene/ det behøvde for å ha god fremgang?

** Manglet teamet /tid/ til å fokusere på meningsfult arbeid?

** Unnlot jeg å gi eller ordne /hjelp/ ved behov eller forespørsel?

** Straffet jeg feil, eller unnlot jeg å finne /læring/ eller muligheter fra nylige seiere eller problemer?

** Utsatte jeg eller andre presentasjon eller debatt av idéer?

* Næring

** Viste jeg /respekt/ for teammedlemmer ved å anerkjenne deres bidrag til fremgang, være oppmerksom på idéne dere, og å behandle dem med profesjonell tillit?

** /Oppmuntret/ jeg medlemmer i teamet når de hadde krevende utfordringer?

** Støttet jeg medlemmer i deres personlig og profesjonelle utfordringer?

** Er det noen følelse av /samhold/ og kameraderi innad i teamet?

* Gift

** Viste jeg /mangel på respekt/ for teammedlemmer ved å unngå å anerkjenne deres bidrag til fremgang, overse idéene deres, eller ved å ikke vise dem profesjonell tillit?

** Gjorde jeg på noen måte teammedlemmer /nedstemte/ (discouraged)?

** /Overså/ jeg medlemmer som hadde personlige eller profesjonelle utfordringer?

** Er det spenninger eller /antagonisme/ mellom medlemmer av teamet, eller mellom medlemmer og meg?

* Arbeidsopplevelse

** /Fikk jeg noen følelse av kvaliteten på teammedlemmenes arbeidsopplevelse i dag?/
- Opplevelser av arbeidet, ledelsen, firmaet
- Følelser
- Motivasjon
- Hvilke spesielle hendelser kan ha påvirket arbeidsopplevelsen i dag?

* Aksjonspunkter

** Hva kan jeg gjøre i morgen for å styke katalysatorene og næringen jeg identifiserte, og bidra til dem som manglet?

** Hva kan jeg gjøre i morgen for å eliminere inhibitorene og giftene jeg identifiserte?
